site_name: PymoNNto
site_url: "https://pymonnto.readthedocs.io/"
site_description: Project documentation with Markdown.
site_author: Marius Vieth

repo_url: https://github.com/trieschlab/PymoNNto
edit_uri: "github.com/trieschlab/PymoNNto"

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust

nav:
    - Home: index.md

    - Introduction:
        - -Installation: Introduction/installation.md
        - -Basics: Introduction/basics.md
        - -Tagging System ['tag']: Introduction/Tagging.md
        - -User Interface: Introduction/User_Interface.md
        - -Input switching: Introduction/input_switch.md
        - -Neuron Dimension: Introduction/Neuron_Dimension.md
        - -Recorder: Introduction/Recorder.md
        - -Event Recorder: Introduction/Event_Recorder.md

    - Fast and efficient code:

        - -Fast processing: Efficiency/fast_processing.md
        - -Storage Manager: Efficiency/StorageManager.md
        - -Evolution: Efficiency/Evolution.md
        - -Cython: Efficiency/cython.md
        - -Conditional Behavior: Efficiency/Conditional_Behavior_Attachment.md

    - Complex Example:
        - -Homeostasis: Complex_Tutorial/Homeostasis.md
        - -Normalization: Complex_Tutorial/Normalization.md
        - -STDP: Complex_Tutorial/STDP.md
        - -Complex Network: Complex_Tutorial/Complex.md

    - Behavior Examples:
        - -Default Homeostatic Mechanism: Behaviors/Default_homeostatic_mechanism.md
        - -Refractory Period: Behaviors/Refractory_Period.md
        - -NOX Diffusion: Behaviors/NOX_Diffusion.md

    - Synapse Behaviors:
        - -Weight initialization: Synapse_Behaviors/Weight_Initialization.md
        - -Receptive fields and connectivity: Synapse_Behaviors/Receptive_Fields.md
        - -Partition: Synapse_Behaviors/Partition.md

    - User Interface Tabs:
        - -Custom UI Tab: UI/cutom_ui_tab.md
        - -Default Tabs:  UI/Default.md
        - -Advanced Tabs: UI/Advanced_Tabs.md
        - -Text Input Tabs: UI/Text_Input_Tabs.md
        - -Basic Tab: UI/Basic_Tab.md
        - -OpenGL Tab: UI/OpenGLTab.md

    - Classical Examples:
        - -Brunel Hakim: Classical/Brunel_Hakim.md
        - -Diesmann_Synfire: Classical/Diesmann_Synfire.md
        - -Hindmarsh Rose: Classical/Hindmarsh_Rose.md
        - -Hodgkin Huxley: Classical/Hodgkin_Huxley.md
        - -Hopfield: Classical/Hopfield.md
        - -Izhikevich: Classical/Izhikevich.md
        - -Leaky Integrate And Fire: Classical/LeakyIntegrateAndFire.md
        - -Wang Buzaki: Classical/Wang_Buzaki.md

    - Experimental:
        - -Differential Equation - Brian 2 - Hybrid: Experimental/Differential_Equation.md
        - -Tensorflow: Experimental/Tensorflow.md

plugins:
    - search