site_name: PymoNNto
site_url: ""
site_description: Project documentation with Markdown.
site_author: Marius Vieth

repo_url: https://github.com/trieschlab/SORNSim
edit_uri: ""

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust

nav:
    - Home: index.md
    - Introduction:
        - PIP installation: Introduction/PIP_installation.md
        - Manual installation: Introduction/Manual_installation.md
    - Basic Tutorial:
        - Basics: Basic_Tutorial/basics.md
        - Synapses and Input: Basic_Tutorial/Synapses_and_Input.md
        - User Interface: Basic_Tutorial/User_Interface.md
    - Complex Tutorial:
        - Homeostasis: Complex_Tutorial/Homeostasis.md
        - Normalization: Complex_Tutorial/Normlaization.md
        - STDP: Complex_Tutorial/STDP.md
        - Complex Network: Complex_Tutorial/ComplexNetwork.md
    - Behaviours:
        -
    - Classical Examples:
          - Brunel Hakim: Classical/Brunel_Hakim.md
          - Diesmann_Synfire: Classical/Diesmann_Synfire.md
          - Hindmarsh Rose: Classical/Hindmarsh_Rose.md
          - Hodgkin Huxley: Classical/Hodgkin_Huxley.md
          - Hopfield: Classical/Hopfield.md
          - Izhikevich: Classical/Izhikevich.md
          - Leaky Integrate And Fire: Classical/LeakyIntegrateAndFire.md
          - Wang Buzaki: Classical/Wang_Buzaki.md
    - Experimental:
        - Differential Equation: Experimental/Differential_Equation.md
        - Tensorflow: Experimental/Tensorflow.md

plugins:
    - search