site_name: PymoNNto
site_url: ""
site_description: Project documentation with Markdown.
site_author: Marius Vieth

repo_url: https://github.com/trieschlab/SORNSim
edit_uri: ""

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust

nav:
    - Home: index.md
    - Introduction:
        - PIP installation: Introduction/PIP_installation.md
        - Manual installation: Introduction/Manual_installation.md
    - Tutorials:
        - Basics: Tutorials/basics.md
        - Synapses and Input: Tutorials/Synapses_and_Input.md
        - User Interface: Tutorials/User_Interface.md
    - Examples:
        - Differential Equation: Examples/Differential_Equation.md
        - Tensorflow: Examples/Tensorflow.md
    - Classical Examples:
          - Brunel Hakim: Classical_Examples/Brunel_Hakim.md
          - Diesmann_Synfire: Classical_Examples/Diesmann_Synfire.md
          - Hindmarsh Rose: Classical_Examples/Hindmarsh_Rose.md
          - Hodgkin Huxley: Classical_Examples/Hodgkin_Huxley.md
          - Hopfield: Classical_Examples/Hopfield.md
          - Izhikevich: Classical_Examples/Izhikevich.md
          - Leaky Integrate And Fire: Classical_Examples/LeakyIntegrateAndFire.md
          - Wang Buzaki: Classical_Examples/Wang_Buzaki.md

plugins:
    - search